{% set name = 'hail' %}
{% set version = '0.2.127' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # the build process requires a repository to set some variables
  # (e.g. version)
  git_url: https://github.com/hail-is/hail.git
  git_rev: {{ version }}
  patches:
    - patches/0001-remove-vendored-libsimdpp.patch
    - patches/0002-remove-vendored-catch2.patch
    - patches/0003-patch-requirements.patch
    - patches/0004-pluggy-old-style-wrappers.patch
    - patches/0005-patch-spark-3.3.2-to-3.4.1.patch

build:
  number: 0
  # avro and others a not available for win
  # openjdk and pyspark not available for s390x
  skip: true  # [py<39 or win or py>311 or s390x]
  entry_points:
    - hailctl = hailtop.hailctl.__main__:main

requirements:
  build:
    - {{ compiler('cxx') }}
    - make      # [linux]
    - patch     # [not win]
    - m2-patch  # [win]
    - git
  host:
    - python
    - pip
    - setuptools
    # pre requisites
    - pytest-runner
    - pyspark >=3.3.2,<=3.4.1
    - openjdk 11.*
    - lz4
    # libsimdpp and catch2 unvendored dependencies
    - libsimdpp
    - catch2
    # hail build needs these here to build hailtop/hailctl
    - aiodns >=2.0.0,<3
    - aiohttp >=3.9,<4
    - azure-identity >=1.6.0,<2
    - azure-mgmt-storage ==20.1.0
    - azure-storage-blob >=12.11.0,<13
    - boto3 >=1.17,<2.0
    - botocore >=1.20,<2.0
    - dill >=0.3.6,<0.4
    - frozenlist >=1.3.1,<2
    - google-auth >=2.14.1,<3
    - google-auth-oauthlib >=0.5.2,<1
    - humanize >=1.0.0,<2
    - janus >=0.6,<1.1
    - nest-asyncio >=1.5.8,<2
    - orjson >=3.6.4,<4
    # - protobuf ==3.20.2
    # we have protobuf 3.20.3
    - protobuf >=3.20.2,<=3.20.3
    # - rich >=12.6.0,<13
    # we have rich 12.5.0
    - rich >=12.5.0,<13
    - typer >=0.9.0,<1
    - python-json-logger >=2.0.2,<3
    - pyyaml >=6.0,<7.0
    - sortedcontainers >=2.4.0,<3
    - tabulate >=0.8.9,<1
    - uvloop >=0.19.0,<1  # [not win]
    - jproperties >=2.1.1,<3
  run:
    - python
    - openjdk 11.*
    - aiodns >=2.0.0,<3
    - aiohttp >=3.9,<4
    - azure-identity >=1.6.0,<2
    - azure-mgmt-storage ==20.1.0
    - azure-storage-blob >=12.11.0,<13
    - boto3 >=1.17,<2.0
    - botocore >=1.20,<2.0
    - dill >=0.3.6,<0.4
    - frozenlist >=1.3.1,<2
    - google-auth >=2.14.1,<3
    - google-auth-oauthlib >=0.5.2,<1
    - humanize >=1.0.0,<2
    - janus >=0.6,<1.1
    - nest-asyncio >=1.5.8,<2
    - orjson >=3.6.4,<4
    # - protobuf ==3.20.2
    # we have protobuf 3.20.3
    - protobuf >=3.20.2,<=3.20.3
    # - rich >=12.6.0,<13
    # we have rich 12.5.0
    - rich >=12.5.0,<13
    - typer >=0.9.0,<1
    - python-json-logger >=2.0.2,<3
    - pyyaml >=6.0,<7.0
    - sortedcontainers >=2.4.0,<3
    - tabulate >=0.8.9,<1
    - jproperties >=2.1.1,<3
    - avro >=1.10,<1.12
    - bokeh >=3,<4
    - decorator <5
    - Deprecated >=1.2.10,<1.3
    - numpy <2
    - pandas >=2,<3
    - parsimonious <1
    - plotly >=5.18.0,<6
    - pyspark >=3.3.2,<=3.4.1
    - requests >=2.31.0,<3
    - scipy >1.2,<1.12
    - uvloop >=0.19.0,<1  # [not win]
    # because pkg_resources is needed
    - setuptools

# skip tests that require a backend or datafiles
{% set tests_to_skip = "test_hadoop_ or test_annotate_intervals_ or test_verify_biallelic or test_table_filter_intervals" %}
{% set tests_to_skip = tests_to_skip + " or test_matrix_filter_intervals or test_filter_intervals_compound_key" %}
{% set tests_to_skip = tests_to_skip + " or test_export_rectangles or test_sparsify_band_ or test_row_intervals_1 or test_sparsify_row_intervals_0" %}
{% set tests_to_skip = tests_to_skip + " or test_parses or test_tlocus_schema_from_rg_matches_scala or test_requester_pays_" %}
{% set tests_to_skip = tests_to_skip + " or test_pedigree or test_slices_with_sparsify or test_exceptions_from_workers_have_stack_traces" %}
{% set tests_to_skip = tests_to_skip + " or test_hail_in_notebook or test_pgenchisq" %}
# ignore test files that require a backend or datafiles
{% set testfiles_to_ignore = "--ignore=test/hail/genetics/test_reference_genome.py --ignore=test/hail/methods/test_king.py --ignore=test/hail/methods/test_simulation.py" %}
{% set testfiles_to_ignore = testfiles_to_ignore + " --ignore=test/hail/methods/relatedness/test_identity_by_descent.py --ignore=test/hail/methods/test_qc.py --ignore=test/hailtop/" %}
{% set testfiles_to_ignore = testfiles_to_ignore + " --ignore=test/hail/matrixtable/test_file_formats.py --ignore=test/hail/experimental/test_experimental.py --ignore=test/hail/expr/test_expr.py" %}
{% set testfiles_to_ignore = testfiles_to_ignore + " --ignore=test/hail/matrixtable/test_matrix_table.py --ignore=test/hail/methods/test_family_methods.py --ignore=test/hail/methods/test_impex.py" %}
{% set testfiles_to_ignore = testfiles_to_ignore + " --ignore=test/hail/methods/test_pca.py --ignore=test/hail/methods/test_skat.py --ignore=test/hail/methods/test_statgen.py" %}
{% set testfiles_to_ignore = testfiles_to_ignore + " --ignore=test/hail/methods/relatedness/test_pc_relate.py --ignore=test/hail/table/test_table.py --ignore=test/hail/vds/test_combiner.py" %}
{% set testfiles_to_ignore = testfiles_to_ignore + " --ignore=test/hail/vds/test_vds.py --ignore=test/hail/utils/test_hl_hadoop_and_hail_fs.py --ignore=test/hail/extract_intervals/" %}

test:
  imports:
    - hail
    - hailtop.batch
  source_files:
    - hail/python/test
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - cd hail/python
    - pytest -v test -k "not ({{ tests_to_skip }})" {{ testfiles_to_ignore }}

about:
  home: https://hail.is
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: |
    Hail is Python-based data analysis tool for working with genomic data.
  description: |
    Hail is an open-source, general-purpose, Python-based data analysis 
    tool with additional data types and methods for working with genomic data.

    Hail is built to scale and has first-class support for multi-dimensional
    structured data, like the genomic data in a genome-wide association study (GWAS).

    Hail is exposed as a Python library, using primitives for distributed queries and
    linear algebra implemented in Scala, Spark, and increasingly C++.
  dev_url: https://github.com/hail-is/hail
  doc_url: https://hail.is/docs/0.2/index.html
extra:
  skip-lints:
    - host_section_needs_exact_pinnings
    - python_build_tool_in_run
  recipe-maintainers:
    - raivivek
