{% set name = 'hail' %}
{% set version = '0.2.127' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/hail-is/hail.git
  git_rev: {{ version }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    # - rsync
  host:
    - python
    - pip
    - pyspark >=3.3.2,<=3.4.1
    - openjdk 11.*
    - lz4
    - libsimdpp
  run:
    - python
    - openjdk 11.*
    - aiodns <3,>=2.0.0
    - aiohttp <4,>=3.9
    - azure-identity <2,>=1.6.0
    - azure-mgmt-storage ==20.1.0
    - azure-storage-blob <13,>=12.11.0
    - boto3 <2.0,>=1.17
    - botocore <2.0,>=1.20
    - dill <0.4,>=0.3.6
    - frozenlist <2,>=1.3.1
    - google-auth <3,>=2.14.1
    - google-auth-oauthlib <1,>=0.5.2
    - humanize <2,>=1.0.0
    - janus <1.1,>=0.6
    - nest-asyncio <2,>=1.5.8
    - orjson <4,>=3.6.4
    - protobuf ==3.20.2
    - rich <13,>=12.6.0
    - typer <1,>=0.9.0
    - python-json-logger <3,>=2.0.2
    - pyyaml <7.0,>=6.0
    - sortedcontainers <3,>=2.4.0
    - tabulate <1,>=0.8.9
    - jproperties <3,>=2.1.1
    - avro <1.12,>=1.10
    - bokeh <4,>=3
    - decorator <5
    - Deprecated <1.3,>=1.2.10
    - numpy <2
    - pandas <3,>=2
    - parsimonious <1
    - plotly <6,>=5.18.0
    - pyspark <=3.4.1,>=3.3.2
    - requests <3,>=2.31.0
    - scipy <1.12,>1.2
    - uvloop <1,>=0.19.0  # [not win]

test:
  imports:
    - hail
    - hailtop.batch

about:
  home: https://hail.is
  dev_url: https://github.com/hail-is/hail
  license: MIT
  license_file: LICENSE
  summary: |
    Hail is Python-based data analysis tool for working with genomic data.

extra:
  skip-lints:
    - uses_vcs_url
  recipe-maintainers:
    - raivivek
